### PR TITLE
bug: contact page made responsive

### PR DESCRIPTION
**Pull request by accodes21**
Made the contact page responsive my adding media queries.
Closes issue #81 
Screen recording:

https://github.com/amittri1025/Whatsapp-Link-Gen/assets/101868279/3c30076a-fa31-4d03-b07e-449c21023093

### CODE REVIEW

**Comment by amittri1025** [comment]
Add more and make those block align in flex column

**Comment by accodes21** [comment]
Can you give more details since I have checked for major mobile devices and its working fine. No major device has width less than 200px.

**Comment by amittri1025** [comment]
Things should stack, something like this on smaller screens.
image

**Comment by accodes21** [comment]
@amittri1025 updated the changes pls check here:
Screen Recording:

https://github.com/amittri1025/Whatsapp-Link-Gen/assets/101868279/8338c133-f475-4559-9181-dd324d1dce47

**Comment by amittri1025** [comment]
Someone, did it in a little good way #81 . Anyway thanks

**Pull request closed without merging**
