### PR TITLE
Styling Fixes

### PR DESCRIPTION
**Pull request by Tanya347**
There were quite a few styling issues that I would like to mention:

Firstly this whatsapp icon that is not really serving any purpose but causing responsive issues and removing the focus from the main content:
image

When the image on the right disappears it doesn't really look symmetric:
image

This image has no correlation to the website:
image

The changes I've introduced include:

- Removing the whatsapp icon and adding a small icon next to the heading:
image

- Replacing the image to something that's more comprehensive:
image

- When image disappears I've made it a little symmetric:
image

There were also a few padding and spacing issues that I've fixed.

Please consider merging this pr. Thanks :)

### CODE REVIEW

**Comment by amittri1025** [comment]
I dont think that big whatsapp, is useless that's looking great on Desktop. Can you please come up with a PR, making that responsive , rest looks great.
Thanks

**Comment by Tanya347** [comment]
Sure, I'll try that.

**Comment by Tanya347** [comment]
Hey @amittri1025 I have made the whatsapp icon responsive, check out the various screen sizes:

Beyond 1200px:
image

Beyond 1000px:
image

Beyond 700px:
image

Beyond 578px:
image

Below 578px (mobile screens):
image

Let me know if anything else needs to be changed :)

**Comment by amittri1025** [comment]
# सूंदर
@Tanya347  Merged.

**Comment by Tanya347** [comment]
धन्यवाद :)

**Comment by amittri1025** [comment]
@Tanya347 Hey is this PR, visible in your Hacktoberfest account ?

**Comment by Tanya347** [comment]
Yes it is, it's under review right now.

**Pull request merged**
