### PR TITLE
Toggle button text changes to Light when Dark Mode applied and vice versa

### PR DESCRIPTION
**Pull request by Sharjeel-Afridi**

### CODE REVIEW

**Comment by amittri1025** [comment]
Post a video of change.

**Comment by Sharjeel-Afridi** [comment]
> Post a video of change.


https://github.com/amittri1025/Whatsapp-Link-Gen/assets/52808124/861534d6-2e8e-4cbf-bb81-cb8c0e084094

ignore the change in color of light button, those are local changes.

**Comment by Sharjeel-Afridi** [comment]
https://github.com/amittri1025/Whatsapp-Link-Gen/assets/52808124/b7cf26a5-4654-45b5-a27c-59d97f85f4b5

**Comment by amittri1025** [comment]
lgtm

**Pull request merged**
