### PR TITLE
[Fixes #5] Fixed Number Input Issue

### LINKED ISSUE #5: [GSSoC'23] Check if Number is valid and Input is filled
#### Problem
Currently link is generated even when we don't provide the number.

#### Expected result
This should not happen. Instead user should be shown error by turning input box red or by displaying proper message.

### PR DESCRIPTION
**Pull request by ritik48**
This pr fixes #5 

Now if number is not provided and 'Generate link' is clicked, then link will not generate instead input will turn red showing err. And now mobile input will only accept number.

whatsapp link solved

### CODE REVIEW

**Comment by amittri1025** [comment]
Congratulations 🥳...Looking forward for more contributions from your side.

**Comment by amittri1025** [comment]
@ritik48 There's one more fix need, users cannot enter 0 in the Mobile Number Input. Kindly Fix

**Comment by amittri1025** [comment]
Hey @ritik48 are you there should I assign it to someone else.

**Comment by ritik48** [comment]
@amittri1025 this pr #12 fixes the issue.

**Pull request merged**
