### PR TITLE
Updated the README.md file and improved the documentation

### PR DESCRIPTION
**Pull request by H-SM**

### CODE REVIEW

**Comment by H-SM** [comment]
hey @amittri1025, I have worked on the issues #36 and #6 over this PR. I hope the changes met your expectations over it... Tt would be a lot helpful if you could assign a `hacktober-accepted` label over this PR.
Thanks.

**Comment by amittri1025** [comment]
@H-SM Update the Readme with Full Recording of using the web app.

**Comment by H-SM** [comment]
hey @amittri1025, I have added a full recording of the web app now... It's good to go from my side. Hope the PR will get merged up soon.
Thanks.

ps.: please don't forget the label of `hacktoberfest-accepted` over it.

**Comment by amittri1025** [comment]
LGTM :)

**Pull request merged**
