### PR TITLE
Add my contribution

### PR DESCRIPTION
**Pull request by priyanshu8584**
Modified the  logos and added relevant colors to them
Added modifications to rock button
 #86

### CODE REVIEW

**Comment by amittri1025** [comment]
ADD A SCREENSHOT OR RECORDING

**Comment by priyanshu8584** [comment]
Screenshot 2023-10-11 121931

**Comment by priyanshu8584** [comment]
Screenshot 2023-10-11 122241

**Comment by priyanshu8584** [comment]
Screenshot 2023-10-11 122358
Screenshot 2023-10-11 122428

**Comment by priyanshu8584** [comment]
please merge this changes under hacktoberfest-accepted label

**Comment by priyanshu8584** [comment]
@amittri1025

**Comment by amittri1025** [comment]
Conflicting. Kindly open a new PR.

**Pull request closed without merging**
